name = "Wild Wild West 0 . 1 . 0"
author = "TheSkyDude"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e881df35bdb96801be84fd396a889d6dca10cf51fd015b86c4531aaaa66e9a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
