name = "Wild Wild West"
author = "TheSkyDude"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e95ecb6c3e2787b216079b4be029bbf217fc43f43e2b3fd6bd8a38ccbae1a761"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
