name = "Wild Wild West"
author = "TheSkyDude"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f99a52c04cf5cd8eb525f74090526bdaab0a3f842ea83bd295581fc61e0ef21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
