#Create Aeronautics Toolgun Client Settings
#Sat May 09 09:30:03 EDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=64
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=210
rotationStep=15
scalePercent=100
selectedFile=native\:chinookv1.excraft
snapMode=HIT
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
