#Create Aeronautics Toolgun Client Settings
#Fri May 08 22:45:25 EDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=64
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=0
rotationStep=15
scalePercent=100
selectedFile=
snapMode=LEGACY
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
